### ISSUE TITLE
Due time

### ISSUE THREAD

**Issue by Labrox** [kanbantool/scripts#17]
I want a function where i can put in a due time (with and without date).
We use Kanbantool for everyday task, and want to have a due time.
example:
Update the mail list and share it with the office
Due - Today 14:00.

12:00 it turns yellow (close to due time)
13:30 it turns red (really close to due time).

I dont know how to use Javascripts or CSS, so i need help to making this function.

**Comment by akachemical** [comment]
Hi Labrox,

I see what you mean. Unfortunately, we do not offer custom development at this time. In other words, custom scripts can be used in Kanban Tool, under the condition that users create them themselves. Sorry. 

Please let me know if I may be of any other assistance.
Best,
Anna
Kanban Tool Support
