### ISSUE TITLE
Power-Ups > Developer tools: Link to script has no effect (resolved)

### ISSUE THREAD

**Issue by bjohas** [kanbantool/scripts#18]
E.g. pasting https://raw.githubusercontent.com/kanbantool/scripts/sdk-scripts/change-column/change-column.js into "Enter links to the selected scripts:" takes no effect. (However, pasting the script content into "Or enter code directly into the boxes below:" does work.)

Any ideas on what the problem might be? Is it the URL? Or is this a bug?

Thanks!!

**Comment by akachemical** [comment]
Please note, you're only meant to paste this portion (/scripts/change-column/change-column.js) of the link to the "Enter links to the selected scripts:" slot. It will then work OK. Thank you for asking!
![01](https://user-images.githubusercontent.com/9267356/54906433-89536f00-4ee3-11e9-8c44-75c3e37828e4.png)

**Comment by bjohas** [comment]
Ahhhh - thank you!
