### ISSUE TITLE
Scripts to bring footer menu for "edit card" in line with "new card" (request)

### ISSUE THREAD

**Issue by bjohas** [kanbantool/scripts#19]
When you create a new card, you have the following in the footer.

Create and close; Create and add next; Create and edit 

(The "X" abandons the card creation.) But when you edit a card, you don't have a bottom menu, and the "X" closes the card (saved). The save done script (https://github.com/kanbantool/scripts/blob/sdk-scripts/save-done/save-done.js)  adds a "Move to done" to the footer.

My request is for additional scripts that bring the "edit card" footer in line with "new card" footer, i.e. script(s) that adds this to the footer:

Save; Save and close; Save and duplicate; Move to done. 

Obviously the "move to done" script exists, but the other scripts would be good. Of course, the save isn't needed, as the cards are auto-saved. However, it helps to reassure less experienced users, so it would be lovely. I am also not fussed about the exact text, as that can easily be added in the script.

(I would also love a script, that changes the "X" to a tick when cards are opened for editing. Or changes the "X" when creating new cards to a red "X" or similar, to indicate the different function.)

**Comment by bjohas** [comment]
This image https://github.com/kanbantool/scripts/blob/sdk-scripts/save-done/preview.png suggests that there should be a 'save' and 'save and close' button anyway.

I cannot see those buttons (OS X, latest version of Chrome). I am pretty sure they were there in a previous version. Could this be a bug?

**Comment by akachemical** [comment]
Thank you for these suggestions. They were noted down for future consideration.

**Comment by akachemical** [comment]
Yes, the "save" and "save and close" buttons were present in a much older Kanban Tool version only, and were abandoned a few years back.

**Comment by bjohas** [comment]
I've added a PR for the close button - the code was fairly easy to guess. However, it would obviously be good if you could look over it. The duplicate button is less clear to me - for now :)
